# Nairobi club Instagram hashtags
# NO # symbols. NO spaces. Lowercase only.
# The scraper adds # automatically when building URLs.

INSTAGRAM_HASHTAGS = {
    # Core clubs
    "alchemist254": "The Alchemist Bar",
    "burudaniaddress": "Burudani Address",
    "quiverlounge": "Quiver Lounge",
    "kikao": "Kikao Lounge",
    "40forty": "40Forty Lounge",
    "milanlounge": "Milan Lounge",
    "gallosbar": "Gallo's Bar",

    # Quiver branches
    "quiverkilimani": "Quiver Kilimani",
    "quiverthikaroad": "Quiver Thika Road",

    # Brew Bistro branches
    "brewbistro": "Brew Bistro",
    "brewbistrorooftop": "Brew Bistro Rooftop",

    # More venues
    "k1klubhouse": "K1 Klub House",
    "1824whiskeybar": "1824 Whiskey Bar & Lounge",
    "thebarnextdoor": "The Bar Next Door",
    "blacksamurai": "Black Samurai",
    "milannairobi": "Milan",
    "kettlehouse": "Kettle House",
    "tribeka": "Tribeka",
    "havanabar": "Havana Bar",
    "gipsybar": "Gipsy Bar",
    "bndlounge": "BND Lounge",
    "replaylounge": "Replay Lounge",
    "sankararooftop": "Sankara Rooftop",
    "treehousenbo": "Treehouse",
    "priveenairobi": "Privee",
    "clubgemini": "Club Gemini",
    "tamashawestlands": "Tamasha Westlands",
    "blendlounge": "Blend Lounge",
    "luxxlounge": "Luxx Lounge",
    "kizalounge": "Kiza Lounge",
    "bluemartini": "Blue Martini",
    "mjazzwestlands": "MJ's Bar and Grill",
    "skylounge": "Sky Lounge",
    "galileolounge": "Galileo Lounge",
    "choicespub": "Choices Pub",
    "bclub": "B Club",
    "safariparkhotel": "Safari Park Club",
    "velvetlounge": "Velvet Lounge",
    "clubillusion": "Club Illusion",
    "casablancaclub": "Casablanca Club",
    "hypnoticamombasa": "Hypnotica",
    "liquidcash": "Liquid Cash",
    "shootersanddips": "Shooters & Dips",
    "spassolounge": "Spasso Lounge",
    "redroom": "Red Room",
    "caramellounge": "Caramel Lounge",
    "whisperske": "Whispers",
    "xoxolounge": "XOXO Lounge",
    "dungeonlounge": "Dungeon Lounge",
    "oysterbay": "Oyster Bay",
    "simmerslounge": "Simmers Restaurant & Lounge",
    "roadhousegrill": "Road House Grill",
    "mercurylounge": "Mercury Lounge",
    "bubbleslounge": "Bubbles Lounge",
    "fortylounge": "Forty Lounge",
    "lacasa": "La Casa",
    "platinum7d": "Platinum 7D",
    "mojoslounge": "Mojos Lounge",
    "skyluxlounge": "Skylux Lounge",
    "euphorialounge": "Euphoria Lounge",
    "cavallilounge": "Cavalli Lounge",
    "livvibez": "Liv Vibez Lounge",
    "clickslounge": "Clicks Lounge",
    "thenode": "The Node",
    "rooftop254": "Rooftop 254",
    "bqlounge": "BQ Lounge",
    "club034": "Club 034",
    "florida2000": "Florida 2000",
    "tapascielo": "Tapas Cielo",
    "theaddresslounge": "The Address Lounge",
    "h2oclub": "H2O Club",
    "clubdaplace": "Club Da Place",
    "tamashaeldoret": "Tamasha Eldoret",
    "zero01lounge": "Zero 01 Lounge",
    "xsmillionaires": "XS Millionaires",
    "brewtaproom": "Brew Tap Room",
    "taverngrill": "Tavern Grill",
    "moonshinebeachbar": "Moonshine Beach Bar",
    "shughulilounge": "Shughuli Lounge",
    "tipsyclub": "Tipsy Club",
    "garagelounge": "Garage Lounge",
    "themist": "The Mist",
    "blendx": "Blend X",
    "district61": "District 61",
    "luxelounge": "Luxe Lounge",
    "mocaloca": "Moca Loca",
    "orbitlounge": "Orbit Lounge",
    "vegalounge": "Vega Lounge",
    "clubicon": "Club Icon",
    "thehoodlounge": "The Hood Lounge",
    "viproom": "VIP Room",
    "infinitylounge": "Infinity Lounge",
    "clubvolume": "Club Volume",
    "captainsterrace": "Captain's Terrace",
    "ibizaclub": "Ibiza Club",
    "hustlelounge": "Hustle Lounge",
    "clubenkarre": "Club Enkarre",
    "maziwalounge": "Maziwa Lounge",
    "bluesprings": "Blue Springs Hotel Lounge",
    "ashakigrill": "Ashaki Grill",
    "barbarnairobi": "Bar Bar",
    "switchlounge": "Switch Lounge",
    "pulselounge": "Pulse Lounge",
    "cocojambo": "Coco Jambo Lounge",
    "nativesbar": "Natives Bar",
    "bacchuslounge": "Bacchus Lounge",
    "skybarnairobi": "Skybar",
    "onyxlounge": "Onyx Lounge",
    "chromeclub": "Chrome Club",
    "altituderooftop": "Altitude Rooftop",
    "jsfreshbar": "J's Fresh Bar",
    "casavera": "Casa Vera Lounge",
    "club47": "Club 47",
    "neolounge": "Neo Lounge",
    "monroelounge": "Monroe Lounge",
}

# Twitter/X hashtags and keywords to monitor
TWITTER_HASHTAGS = {
    "nairobinightlife": "General Nairobi",
    "sherehe": "General Nairobi",
    "shereheke": "General Nairobi",
    "westlandsnightlife": "Westlands",
    "kilimaninights": "Kilimani",
    "alchemist254": "The Alchemist Bar",
    "k1klubhouse": "K1 Klub House",
    "quiverlounge": "Quiver Lounge",
    "brewbistro": "Brew Bistro",
    "40forty": "40Forty Lounge",
}

# Direct venue mentions (not hashtags)
TWITTER_KEYWORDS = [
    "Alchemist Nairobi",
    "K1 Klub House",
    "Quiver Lounge",
    "Brew Bistro Nairobi",
    "40Forty Lounge",
    "Milan Lounge",
    "Havana Bar",
    "Gipsy Bar",
    "Tribeka Nairobi",
]

# Scraper settings
SETTINGS = {
    "max_posts_per_venue": 20,        # Posts per hashtag (keep low to avoid blocks)
    "max_tweets_per_hashtag": 15,     # Tweets per hashtag
    "scrape_interval_minutes": 30,    # How often to run (30 min = safer)
    "headless": True,
    "decay_hours": 3,                 # Pulse decay window
}