"""Add Squads Phase 7

Revision ID: 53b421a606a4
Revises: 735c090fe2a2
Create Date: 2026-04-17 18:46:00.790334

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53b421a606a4'
down_revision: Union[str, Sequence[str], None] = '735c090fe2a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('squads',
    sa.Column('squad_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('invite_code', sa.String(length=8), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['devices.device_id'], ),
    sa.PrimaryKeyConstraint('squad_id')
    )
    op.create_index(op.f('ix_squads_invite_code'), 'squads', ['invite_code'], unique=True)
    op.create_table('squad_members',
    sa.Column('squad_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.squad_id'], ),
    sa.PrimaryKeyConstraint('squad_id', 'device_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('squad_members')
    op.drop_index(op.f('ix_squads_invite_code'), table_name='squads')
    op.drop_table('squads')
    # ### end Alembic commands ###
