"""Init PostGIS

Revision ID: 83d70926d323
Revises: 
Create Date: 2026-04-17 15:56:50.787519

"""
import geoalchemy2
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83d70926d323'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('last_pulse_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_index(op.f('ix_devices_device_fingerprint'), 'devices', ['device_fingerprint'], unique=True)
    op.create_table('venues',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('venue_type', sa.String(), nullable=True),
    sa.Column('min_entry_fee', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('venue_id')
    )
    # op.create_index', 'venues', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_venues_location'), 'venues', ['location'], unique=False)
    op.create_index(op.f('ix_venues_name'), 'venues', ['name'], unique=True)
    op.create_table('events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=True),
    sa.Column('event_name', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('event_start', sa.DateTime(), nullable=True),
    sa.Column('event_end', sa.DateTime(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.venue_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_events_event_start'), 'events', ['event_start'], unique=False)
    op.create_table('heat_clusters',
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=True),
    sa.Column('cluster_location', geoalchemy2.types.Geography(geometry_type='POINT', from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('total_pulses', sa.Integer(), nullable=True),
    sa.Column('heat_intensity', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.venue_id'], ),
    sa.PrimaryKeyConstraint('cluster_id')
    )
    # op.create_index', 'heat_clusters', ['cluster_location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_heat_clusters_cluster_location'), 'heat_clusters', ['cluster_location'], unique=False)
    op.create_table('pulses',
    sa.Column('pulse_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('venue_id', sa.UUID(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('intensity', sa.Float(), nullable=True),
    sa.Column('decay_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.venue_id'], ),
    sa.PrimaryKeyConstraint('pulse_id')
    )
    # op.create_index', 'pulses', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_pulses_created_at'), 'pulses', ['created_at'], unique=False)
    op.create_index(op.f('ix_pulses_location'), 'pulses', ['location'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pulses_location'), table_name='pulses')
    op.drop_index(op.f('ix_pulses_created_at'), table_name='pulses')
    op.drop_index('idx_pulses_location', table_name='pulses', postgresql_using='gist')
    op.drop_table('pulses')
    op.drop_index(op.f('ix_heat_clusters_cluster_location'), table_name='heat_clusters')
    op.drop_index('idx_heat_clusters_cluster_location', table_name='heat_clusters', postgresql_using='gist')
    op.drop_table('heat_clusters')
    op.drop_index(op.f('ix_events_event_start'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_venues_name'), table_name='venues')
    op.drop_index(op.f('ix_venues_location'), table_name='venues')
    op.drop_index('idx_venues_location', table_name='venues', postgresql_using='gist')
    op.drop_table('venues')
    op.drop_index(op.f('ix_devices_device_fingerprint'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
